# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87404907205f2d02afe6f23a006822913b22f733bda25e17318350ae8f6f19528744b313cef97be5419aebf5d0941929a9e3de3e08684aae4068d1ffa74a6ff7

test:
  secret_key_base: 2f9ef9d2405a4250a74a633bae87cb8ae5edeeee03ed0e76a7dff2c9fc1b3f9392e8bc355a5955dd7f3e15532913c4f5557ee3238d69555832ece0989b25bb88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
